### ISSUE TITLE
Rare Lua error

### ISSUE THREAD

**Issue by thegrb93** [DougTy/gibmod#8]
```
[ERROR] addons/gibmod/lua/autorun/gibmod2.lua:671: attempt to index a nil value
  1. GibMod_DeathRagdoll - addons/gibmod/lua/autorun/gibmod2.lua:671
   2. GibMod_HandleDeath - addons/gibmod/lua/autorun/gibmod2.lua:817
    3. GibMod_DoPlayerDeath - addons/gibmod/lua/autorun/gibmod2.lua:882
     4. unknown - addons/gibmod/lua/autorun/gibmod2.lua:888
```
GetPhysicsObjectNum returns nil for some strange reason sometimes.

Maybe GetClosestBone isn't working right?

**Comment by DougTy** [comment]
Line 671 is just a comment for me, [is this the same line?](https://github.com/DougTy/gibmod/blob/master/lua/autorun/gibmod2.lua#L703)

Does changing ```local closest_bone = -1``` to ```0``` in [GetClosestBone](https://github.com/DougTy/gibmod/blob/master/lua/autorun/gibmod2.lua#L482) solve the issue?
I'm unable to reproduce this to test it myself, but this very well may be the problem.

I don't think -1 is a valid bone index for anything, so defaulting to that is my mistake. However, ```GetClosestBone``` should always find a bone, so the default -1 should never be returned anyway. The only instance I can see this failing is if the ragdoll has no valid bones, but I'm not sure how that would happen.

Regardless if that's the source of this particular issue or not, I should probably fix it anyway.
Can you verify if this change makes the error go away on your end?

**Comment by thegrb93** [comment]
Yeah 703 is the line for your code. I'll test it when I get back home.

**Comment by thegrb93** [comment]
I think the code should be

```
ragdoll:GetPhysicsObjectNum( ragdoll:TranslatePhysBoneToBone( GetClosestBone( ragdoll, dmginfo:GetDamagePosition() ) ) ):ApplyForceCenter( dmginfo:GetDamageForce() )
```

**Comment by thegrb93** [comment]
Maybe this can be used http://wiki.garrysmod.com/page/Entity/GetHitBoxBone

**Comment by DougTy** [comment]
```GetClosestBone``` is already iterating through and returning phys bones, so that isn't necessary.

Did changing the default value of ```closest_bone``` to 0 not solve the problem?

I'm again unable to reproduce the issue, but my best guess is still that something's causing ```GetClosestBone``` to not recognize any bones as valid, so it's returning the default invalid bone index of -1 from ```closest_bone```. Bones start enumerating at 0, so -1 definitely isn't a valid index for any model.

The big question is why certain ragdolls (sometimes?) aren't giving us any valid bones, so perhaps this could be related to something specific, like custom models or bone merging? Some kind of player clothing system maybe? Just a shot in the dark, but any context to reproduce the issue would be invaluable.

I've gone ahead and changed the initial value of ```closest_bone``` to 0 in 789c13b, as that's definitely wrong and needed fixing either way. If you can try that out and see if it works, it'd be nice to narrow that down at least. As it's a rare error, it may take some time before we're sure if it's fully disappeared or not.

**Comment by thegrb93** [comment]
Oh, I was thinking GetClosestBone returned a bone rather than a physobj index. Maybe TranslatePhysBoneToBone fails for certain ragdolls.

**Comment by DougTy** [comment]
Not entirely sure off the top of my head. I'm positive I had a good reason at the time, though. Think it may have been because we need to check the result of ```GetClosestBone``` to see if it's a headshot or not, and I vaguely remember it occasionally returning physbones that had no valid corresponding named bones or something like that. Very strange problem, that was the best/simplest solution at the time.
There may be a better way to do it, but I'm pretty sure the issue lies in the ```closest_bone = -1``` problem. Can you confirm if the change in 789c13b solved the error or not? I would prefer to eliminate that possibility before delving into less trivial solutions.

**Comment by thegrb93** [comment]
I don't really want to do that because it would just default the bone to 0 if it can't find anything and I'd rather find the root of the problem.

**Comment by thegrb93** [comment]
I've been getting the error a lot more frequently though so I guess I'll do it anyway.

**Comment by DougTy** [comment]
I don't think it's anything serious. It's definitely a curious issue, and I'd be interested to know the underlying cause, but so long as everything still works and looks right, then surely that's a perfectly acceptable solution? However, we still don't know even know if it does anything, so it's worth a try. For all we know the problem could be completely unrelated.

I'd love to help get to the bottom of it, but I'm truly completely unable to reproduce the error. If you could tell me something to lead me in the right direction; what's generally happening when it occurs, if anything isn't functioning properly, if there are any custom models in play, any clothing addons that use bone merging or parenting, custom weaponry that has some kind of non-standard damage method, etc... then I'd have something to go on, but right now all I can really offer is a best guess and a shot in the dark.

Using -1 in ```closest_bone``` is definitely wrong though, as it's meant to return that initial value if it can't find any bones for whatever reason, and -1 is definitely not a valid bone index, so that needed fixing anyway. Once we can confirm whether this makes the error go away or not and if the change alters the addon's behaviour at all, then we'll at least have a better idea of what that reason is if there's still issue based on what happens, as right now this is really our only concrete lead.

**Comment by thegrb93** [comment]
Looks like the error is gone. Don't know what the consequence of choosing 0 when it can't find a closest joint would cause, but oh well.

**Comment by thegrb93** [comment]
Error happened again. I traced it to GetPhysicsObjectNum returning nil. Don't know what the bone number was that caused it.

**Comment by DougTy** [comment]
I can add more fallbacks to 0 if `GetPhysicsObjectNum` fails, but otherwise I'm really not sure what to do.

Are these custom models? Again, without any context or ability to reproduce, I can't be of much use here.

**Comment by thegrb93** [comment]
Yeah the rigging is weird on some of these models. I think it's the Blaziken player model.
